# -*- coding: utf-8 -*-
"""Paper3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NP1lAphDLzHj2xATiOsiXwcSicnmq8HI
"""

from google.colab import drive
drive.mount('/content/drive')

import os

os.environ['KAGGLE_USERNAME'] = 'esvsresearchhub'
os.environ['KAGGLE_KEY'] = 'KGAT_c12a56a462df87bfb73059139361eadd'

pip install kaggle

import os
import subprocess

def run_with_progress(cmd):
    process = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1
    )
    for line in process.stdout:
        print(line, end="")
    process.wait()
    if process.returncode != 0:
        print("Error occurred!")
    else:
        print(" Done!\n")

def download(dataset, path, unzip=True):
    os.makedirs(path, exist_ok=True)
    print(f"\n Downloading: {dataset}")

    cmd = [
        "kaggle", "datasets", "download",
        "-d", dataset,
        "-p", path
    ]

    if unzip:
        cmd.append("--unzip")

    run_with_progress(cmd)


download("toxicmender/20bn-jester", "data/gesture", unzip=False)


download("himaniishah/egohands", "data/gesture", unzip=True)

print(" Gesture datasets downloaded!")

import os
import subprocess

def run_with_progress(cmd):
    process = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1
    )
    for line in process.stdout:
        print(line, end="")
    process.wait()
    if process.returncode != 0:
        print(" Error occurred!")
    else:
        print(" Done!\n")

def download(dataset, path):
    os.makedirs(path, exist_ok=True)
    print(f"\n Downloading: {dataset}")

    cmd = [
        "kaggle", "datasets", "download",
        "-d", dataset,
        "-p", path,
        "--unzip"
    ]

    run_with_progress(cmd)

download("shahliza27/ur-fall-detection-dataset", "data/fall")
download("soumicksarker/multiple-cameras-fall-dataset", "data/fall")

download("phylake1337/fire-dataset", "data/fire")
download("malligasenthil/bowfire", "data/fire")
download("obulisainaren/forest-fire-c4", "data/fire")

print(" Fall + Fire datasets downloaded!")

import zipfile
import os

def unzip_all(folder):
    for file in os.listdir(folder):
        if file.endswith(".zip"):
            path = os.path.join(folder, file)
            print(f"Unzipping: {file}")
            with zipfile.ZipFile(path, 'r') as zip_ref:
                zip_ref.extractall(folder)
            print(f"Done: {file}")

unzip_all("data/gesture")
unzip_all("data/fall")
unzip_all("data/fire")

import os

print("Gesture:", os.listdir("data/gesture"))
print("Fall:", os.listdir("data/fall"))
print("Fire:", os.listdir("data/fire"))

import os
import shutil

src = "data/fire"
dst_fire = "data/fire_clean/fire"
dst_no_fire = "data/fire_clean/no_fire"

os.makedirs(dst_fire, exist_ok=True)
os.makedirs(dst_no_fire, exist_ok=True)

for file in os.listdir(src):
    if file.endswith(".png"):
        if "not_fire" in file:
            shutil.copy(os.path.join(src, file), dst_no_fire)
        elif "fire" in file:
            shutil.copy(os.path.join(src, file), dst_fire)

from sklearn.model_selection import train_test_split
import os
import shutil

def split_class(src_folder, train_folder, test_folder):
    files = os.listdir(src_folder)
    train, test = train_test_split(files, test_size=0.2, random_state=42)

    for f in train:
        shutil.copy(os.path.join(src_folder, f), train_folder)
    for f in test:
        shutil.copy(os.path.join(src_folder, f), test_folder)

import os
import shutil
from sklearn.model_selection import train_test_split

def split_data(src, train_dst, test_dst):
    files = os.listdir(src)
    train, test = train_test_split(files, test_size=0.2, random_state=42)

    os.makedirs(train_dst, exist_ok=True)
    os.makedirs(test_dst, exist_ok=True)

    for f in train:
        shutil.copy(os.path.join(src, f), train_dst)
    for f in test:
        shutil.copy(os.path.join(src, f), test_dst)

split_data("data/fire_clean/fire", "data/fire_final/train/fire", "data/fire_final/test/fire")
split_data("data/fire_clean/no_fire", "data/fire_final/train/no_fire", "data/fire_final/test/no_fire")

import tensorflow as tf

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "data/fire_final/train",
    image_size=(224, 224),
    batch_size=32
)

test_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "data/fire_final/test",
    image_size=(224, 224),
    batch_size=32
)

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models

base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224,224,3))
base_model.trainable = False

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(2, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=10
)

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

y_true = []
y_pred = []

for images, labels in test_ds:
    preds = model.predict(images)
    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(preds, axis=1))

print(classification_report(y_true, y_pred))
print(confusion_matrix(y_true, y_pred))

import tensorflow as tf

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "data/fire_final/train",
    image_size=(224, 224),
    batch_size=32
)

test_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "data/fire_final/test",
    image_size=(224, 224),
    batch_size=32
)

# Normalize (VERY IMPORTANT)
train_ds = train_ds.map(lambda x, y: (x/255.0, y))
test_ds = test_ds.map(lambda x, y: (x/255.0, y))

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.1),
    tf.keras.layers.RandomZoom(0.1),
])

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models

base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(224, 224, 3)
)

# Freeze first layers
for layer in base_model.layers[:-30]:
    layer.trainable = False

# Unfreeze last layers
for layer in base_model.layers[-30:]:
    layer.trainable = True

model = models.Sequential([
    data_augmentation,
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(2, activation='softmax')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=15
)

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

y_true = []
y_pred = []

for images, labels in test_ds:
    preds = model.predict(images)
    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(preds, axis=1))

print(classification_report(y_true, y_pred))
print(confusion_matrix(y_true, y_pred))

import os
import shutil
import random

def add_more_data(src_folder, dst_folder, num_samples=100):
    files = [f for f in os.listdir(src_folder) if f.endswith(".png")]
    selected = random.sample(files, min(num_samples, len(files)))

    for f in selected:
        shutil.copy(os.path.join(src_folder, f), dst_folder)


add_more_data("data/fire_clean/fire", "data/fire_final/train/fire", 100)
add_more_data("data/fire_clean/no_fire", "data/fire_final/train/no_fire", 100)

print("Extra data added")

import tensorflow as tf

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "data/fire_final/train",
    image_size=(224, 224),
    batch_size=32
)

test_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "data/fire_final/test",
    image_size=(224, 224),
    batch_size=32
)


train_ds = train_ds.map(lambda x, y: (x/255.0, y))
test_ds = test_ds.map(lambda x, y: (x/255.0, y))

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.00005),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print("Model recompiled with lower LR")

history2 = model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=3
)

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

y_true = []
y_pred = []

for images, labels in test_ds:
    preds = model.predict(images)
    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(preds, axis=1))

print(classification_report(y_true, y_pred))
print(confusion_matrix(y_true, y_pred))

import matplotlib.pyplot as plt
import numpy as np

class_names = ["fire", "no_fire"]  # adjust if needed

plt.figure(figsize=(10,10))

for images, labels in test_ds.take(1):
    preds = model.predict(images)

    for i in range(9):
        ax = plt.subplot(3, 3, i+1)
        img = images[i].numpy()

        pred_label = np.argmax(preds[i])
        confidence = np.max(preds[i])

        plt.imshow(img)
        plt.title(f"Pred: {class_names[pred_label]}\nConf: {confidence:.2f}")
        plt.axis("off")

plt.show()

plt.figure(figsize=(10,10))

count = 0

for images, labels in test_ds:
    preds = model.predict(images)

    for i in range(len(images)):
        pred = np.argmax(preds[i])
        true = labels[i].numpy()

        if pred != true:
            ax = plt.subplot(3, 3, count+1)
            plt.imshow(images[i].numpy())
            plt.title(f"Wrong\nPred: {class_names[pred]} | True: {class_names[true]}")
            plt.axis("off")

            count += 1
            if count == 9:
                break
    if count == 9:
        break

plt.show()

plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.legend()
plt.title("Accuracy vs Epochs")
plt.show()

plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.legend()
plt.title("Loss vs Epochs")
plt.show()

from sklearn.metrics import precision_recall_curve
import numpy as np

y_true = []
y_scores = []

for images, labels in test_ds:
    preds = model.predict(images)

    y_true.extend(labels.numpy())
    y_scores.extend(preds[:,1])

y_true = np.array(y_true)
y_scores = np.array(y_scores)

import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_curve, auc

precision, recall, thresholds = precision_recall_curve(y_true, y_scores)
pr_auc = auc(recall, precision)

plt.figure(figsize=(6,5))
plt.plot(recall, precision, label=f'PR AUC = {pr_auc:.3f}')
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")
plt.legend()
plt.grid()

plt.show()

f1_scores = 2 * (precision * recall) / (precision + recall + 1e-8)

plt.figure(figsize=(6,5))
plt.plot(thresholds, f1_scores[:-1])
plt.xlabel("Confidence Threshold")
plt.ylabel("F1 Score")
plt.title("F1 Score vs Confidence Threshold")
plt.grid()

plt.show()

import numpy as np

y_true = []
y_scores = []
y_pred = []

for images, labels in test_ds:
    preds = model.predict(images)

    y_true.extend(labels.numpy())
    y_scores.extend(preds[:, 1])
    y_pred.extend(np.argmax(preds, axis=1))

y_true = np.array(y_true)
y_scores = np.array(y_scores)
y_pred = np.array(y_pred)

print("Sample probabilities:", y_scores[:10])

best_idx = np.argmax(f1_scores[:-1])
best_threshold = thresholds[best_idx]
best_f1 = f1_scores[best_idx]

print("Best Threshold:", best_threshold)
print("Best F1 Score:", best_f1)

import numpy as np
from sklearn.metrics import classification_report

threshold = 0.5
y_pred_thresh = (y_scores >= threshold).astype(int)

print(classification_report(y_true, y_pred_thresh))

import os
import shutil

src = "data/fall/UR_fall_detection_dataset_cam0_rgb"

fall_dir = "data/fall_clean/fall"
normal_dir = "data/fall_clean/normal"

os.makedirs(fall_dir, exist_ok=True)
os.makedirs(normal_dir, exist_ok=True)

for root, dirs, files in os.walk(src):
    for file in files:
        if file.endswith(".png") or file.endswith(".jpg"):
            path = os.path.join(root, file)

            if "fall" in root.lower():
                shutil.copy(path, fall_dir)
            else:
                shutil.copy(path, normal_dir)

print("Basic dataset created")

import random

def limit_images(folder, limit=600):
    files = os.listdir(folder)
    if len(files) > limit:
        remove = random.sample(files, len(files)-limit)
        for f in remove:
            os.remove(os.path.join(folder, f))

limit_images("data/fall_clean/fall", 600)
limit_images("data/fall_clean/normal", 600)

from sklearn.model_selection import train_test_split
import shutil
import os

def split_data(src, train_dst, test_dst):
    files = os.listdir(src)
    train, test = train_test_split(files, test_size=0.2, random_state=42)

    os.makedirs(train_dst, exist_ok=True)
    os.makedirs(test_dst, exist_ok=True)

    for f in train:
        shutil.copy(os.path.join(src, f), train_dst)
    for f in test:
        shutil.copy(os.path.join(src, f), test_dst)

split_data("data/fall_clean/fall", "data/fall_final/train/fall", "data/fall_final/test/fall")
split_data("data/fall_clean/normal", "data/fall_final/train/normal", "data/fall_final/test/normal")

import os

print("Fall:", len(os.listdir("data/fall_clean/fall")))
print("Normal:", len(os.listdir("data/fall_clean/normal")))

import os
import shutil

src = "data/fall/UR_fall_detection_dataset_cam0_rgb"

fall_dir = "data/fall_clean/fall"
normal_dir = "data/fall_clean/normal"

os.makedirs(fall_dir, exist_ok=True)
os.makedirs(normal_dir, exist_ok=True)

for root, dirs, files in os.walk(src):
    for file in files:
        if file.endswith(".png") or file.endswith(".jpg"):
            path = os.path.join(root, file)


            if "fall" in root.lower():
                shutil.copy(path, fall_dir)
            else:
                shutil.copy(path, normal_dir)

print("Rebuilt dataset")

print("Fall:", len(os.listdir("data/fall_clean/fall")))
print("Normal:", len(os.listdir("data/fall_clean/normal")))

import os
import shutil

src = "data/fall/UR_fall_detection_dataset_cam0_rgb"

fall_dir = "data/fall_clean/fall"
normal_dir = "data/fall_clean/normal"

os.makedirs(fall_dir, exist_ok=True)
os.makedirs(normal_dir, exist_ok=True)

for root, dirs, files in os.walk(src):
    for file in files:
        if file.endswith(".png") or file.endswith(".jpg"):
            path = os.path.join(root, file)

            folder = root.lower()

            if "fall" in folder:
                shutil.copy(path, fall_dir)
            elif "adl" in folder:
                shutil.copy(path, normal_dir)

print("Dataset fixed")

import os

print("Fall:", len(os.listdir("data/fall_clean/fall")))
print("Normal:", len(os.listdir("data/fall_clean/normal")))

for root, dirs, files in os.walk("data/fall"):
    print(root)

import os
import shutil

src = "data/fall/UR_fall_detection_dataset_cam0_rgb"

fall_dir = "data/fall_clean/fall"
normal_dir = "data/fall_clean/normal"

os.makedirs(fall_dir, exist_ok=True)
os.makedirs(normal_dir, exist_ok=True)

fall_count = 0
normal_count = 0

for root, dirs, files in os.walk(src):
    folder = os.path.basename(root).lower()

    for file in files:
        if file.endswith(".png") or file.endswith(".jpg"):
            path = os.path.join(root, file)

            if "fall-" in folder:
                shutil.copy(path, fall_dir)
                fall_count += 1

            elif "adl-" in folder:
                shutil.copy(path, normal_dir)
                normal_count += 1

print("Fall images:", fall_count)
print("Normal images:", normal_count)
print("Dataset fixed correctly")

import os

print("Fall:", len(os.listdir("data/fall_clean/fall")))
print("Normal:", len(os.listdir("data/fall_clean/normal")))

import random

def limit_images(folder, limit=600):
    files = os.listdir(folder)
    if len(files) > limit:
        remove = random.sample(files, len(files)-limit)
        for f in remove:
            os.remove(os.path.join(folder, f))

limit_images("data/fall_clean/fall", 600)
limit_images("data/fall_clean/normal", 600)

from sklearn.model_selection import train_test_split
import shutil
import os

def split_data(src, train_dst, test_dst):
    files = os.listdir(src)
    train, test = train_test_split(files, test_size=0.2, random_state=42)

    os.makedirs(train_dst, exist_ok=True)
    os.makedirs(test_dst, exist_ok=True)

    for f in train:
        shutil.copy(os.path.join(src, f), train_dst)
    for f in test:
        shutil.copy(os.path.join(src, f), test_dst)

split_data("data/fall_clean/fall", "data/fall_final/train/fall", "data/fall_final/test/fall")
split_data("data/fall_clean/normal", "data/fall_final/train/normal", "data/fall_final/test/normal")

print("Split done")

import os
import random

def balance_data(folder, target_size):
    files = os.listdir(folder)
    if len(files) > target_size:
        remove = random.sample(files, len(files) - target_size)
        for f in remove:
            os.remove(os.path.join(folder, f))

target = min(
    len(os.listdir("data/fall_clean/fall")),
    len(os.listdir("data/fall_clean/normal"))
)

balance_data("data/fall_clean/fall", target)
balance_data("data/fall_clean/normal", target)

print("Balanced dataset size:", target)

import shutil


shutil.rmtree("data/fall_final", ignore_errors=True)


from sklearn.model_selection import train_test_split
import os

def split_data(src, train_dst, test_dst):
    files = os.listdir(src)
    train, test = train_test_split(files, test_size=0.2, random_state=42)

    os.makedirs(train_dst, exist_ok=True)
    os.makedirs(test_dst, exist_ok=True)

    for f in train:
        shutil.copy(os.path.join(src, f), train_dst)
    for f in test:
        shutil.copy(os.path.join(src, f), test_dst)

split_data("data/fall_clean/fall", "data/fall_final/train/fall", "data/fall_final/test/fall")
split_data("data/fall_clean/normal", "data/fall_final/train/normal", "data/fall_final/test/normal")

print("Re-split done")

history = model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=10
)

import tensorflow as tf

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "data/fall_final/train",
    image_size=(224, 224),
    batch_size=32
)

test_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "data/fall_final/test",
    image_size=(224, 224),
    batch_size=32
)

train_ds = train_ds.map(lambda x, y: (x/255.0, y))
test_ds = test_ds.map(lambda x, y: (x/255.0, y))

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

y_true = []
y_pred = []

for images, labels in test_ds:
    preds = model.predict(images)
    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(preds, axis=1))

print(classification_report(y_true, y_pred))
print(confusion_matrix(y_true, y_pred))

import os
import random
import shutil

src = "data/fall/UR_fall_detection_dataset_cam0_rgb"

fall_folders = []
normal_folders = []

for folder in os.listdir(src):
    path = os.path.join(src, folder)
    if os.path.isdir(path):
        if "fall-" in folder:
            fall_folders.append(path)
        elif "adl-" in folder:
            normal_folders.append(path)

from sklearn.model_selection import train_test_split

fall_train, fall_test = train_test_split(fall_folders, test_size=0.2, random_state=42)
normal_train, normal_test = train_test_split(normal_folders, test_size=0.2, random_state=42)

def copy_images(folder_list, dst):
    os.makedirs(dst, exist_ok=True)

    for folder in folder_list:
        for file in os.listdir(folder):
            if file.endswith(".png") or file.endswith(".jpg"):
                shutil.copy(os.path.join(folder, file), dst)

copy_images(fall_train, "data/fall_final/train/fall")
copy_images(normal_train, "data/fall_final/train/normal")

copy_images(fall_test, "data/fall_final/test/fall")
copy_images(normal_test, "data/fall_final/test/normal")

import os

print("Train Fall:", len(os.listdir("data/fall_final/train/fall")))
print("Train Normal:", len(os.listdir("data/fall_final/train/normal")))
print("Test Fall:", len(os.listdir("data/fall_final/test/fall")))
print("Test Normal:", len(os.listdir("data/fall_final/test/normal")))

import tensorflow as tf

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "data/fall_final/train",
    image_size=(224, 224),
    batch_size=32
)

test_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "data/fall_final/test",
    image_size=(224, 224),
    batch_size=32
)

train_ds = train_ds.map(lambda x, y: (x/255.0, y))
test_ds = test_ds.map(lambda x, y: (x/255.0, y))

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print("Model ready")

history = model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=10
)

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

y_true = []
y_pred = []

for images, labels in test_ds:
    preds = model.predict(images)
    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(preds, axis=1))

print(classification_report(y_true, y_pred))
print(confusion_matrix(y_true, y_pred))

from sklearn.metrics import precision_recall_curve, auc
import numpy as np
import matplotlib.pyplot as plt

y_true = []
y_scores = []

for images, labels in test_ds:
    preds = model.predict(images)
    y_true.extend(labels.numpy())
    y_scores.extend(preds[:,1])  # probability of "normal" class (class 1)

y_true = np.array(y_true)
y_scores = np.array(y_scores)

precision, recall, thresholds = precision_recall_curve(y_true, y_scores)
pr_auc = auc(recall, precision)

plt.figure(figsize=(6,5))
plt.plot(recall, precision, label=f'PR AUC = {pr_auc:.3f}')
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve (Fall Detection)")
plt.legend()
plt.grid()
plt.show()

print("PR AUC:", pr_auc)

f1_scores = 2 * (precision * recall) / (precision + recall + 1e-8)

plt.figure(figsize=(6,5))
plt.plot(thresholds, f1_scores[:-1])
plt.xlabel("Confidence Threshold")
plt.ylabel("F1 Score")
plt.title("F1 Score vs Threshold (Fall Detection)")
plt.grid()
plt.show()

best_idx = np.argmax(f1_scores[:-1])
print("Best Threshold:", thresholds[best_idx])
print("Best F1:", f1_scores[best_idx])

class_names = ["fall", "normal"]

plt.figure(figsize=(10,10))

for images, labels in test_ds.take(1):
    preds = model.predict(images)

    for i in range(9):
        ax = plt.subplot(3,3,i+1)
        img = images[i].numpy()

        pred = np.argmax(preds[i])
        conf = np.max(preds[i])

        plt.imshow(img)
        plt.title(f"Pred: {class_names[pred]}\nConf: {conf:.2f}")
        plt.axis("off")

plt.show()

plt.figure(figsize=(10,10))
count = 0

for images, labels in test_ds:
    preds = model.predict(images)

    for i in range(len(images)):
        pred = np.argmax(preds[i])
        true = labels[i].numpy()

        if pred != true:
            ax = plt.subplot(3,3,count+1)
            plt.imshow(images[i].numpy())
            plt.title(f"Wrong\nPred: {class_names[pred]} | True: {class_names[true]}")
            plt.axis("off")

            count += 1
            if count == 9:
                break
    if count == 9:
        break

plt.show()

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

fpr, tpr, _ = roc_curve(y_true, y_scores)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f'ROC AUC = {roc_auc:.3f}')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve (Fall Detection)")
plt.legend()
plt.grid()
plt.show()

import matplotlib.pyplot as plt

plt.hist(y_scores[y_true==1], bins=20, alpha=0.7, label="Normal")
plt.hist(y_scores[y_true==0], bins=20, alpha=0.7, label="Fall")

plt.xlabel("Confidence Score")
plt.ylabel("Frequency")
plt.title("Confidence Distribution")
plt.legend()
plt.show()

plt.plot(thresholds, precision[:-1], label="Precision")
plt.plot(thresholds, recall[:-1], label="Recall")

plt.xlabel("Threshold")
plt.ylabel("Score")
plt.title("Precision & Recall vs Threshold")
plt.legend()
plt.grid()
plt.show()

import seaborn as sns
import numpy as np
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred)
cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

sns.heatmap(cm_norm, annot=True, cmap="Blues", fmt=".2f")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Normalized Confusion Matrix")
plt.show()

from tensorflow.keras import layers, models

baseline_model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(224,224,3)),
    layers.MaxPooling2D(),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(2, activation='softmax')
])

baseline_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

baseline_model.fit(train_ds, validation_data=test_ds, epochs=5)

import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score

thresholds_test = [0.3, 0.5, 0.7, 0.79]

for t in thresholds_test:
    y_pred_t = (y_scores >= t).astype(int)
    print(t,
          precision_score(y_true, y_pred_t),
          recall_score(y_true, y_pred_t),
          f1_score(y_true, y_pred_t))

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

y_true = []
y_pred = []

for images, labels in test_ds:
    preds = baseline_model.predict(images)
    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(preds, axis=1))

print(classification_report(y_true, y_pred))
print(confusion_matrix(y_true, y_pred))

model.save("final_fall_model.h5")
baseline_model.save("baseline_model.h5")

import json

with open("history_proposed.json", "w") as f:
    json.dump(history.history, f)

with open("history_baseline.json", "w") as f:
    json.dump(baseline_model.history.history, f)

import pandas as pd
from sklearn.metrics import classification_report

report = classification_report(y_true, y_pred, output_dict=True)
df = pd.DataFrame(report).transpose()

df.to_csv("classification_report.csv")

import numpy as np
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred)
np.save("confusion_matrix.npy", cm)

import pandas as pd

df_preds = pd.DataFrame({
    "y_true": y_true,
    "y_pred": y_pred,
    "y_score": y_scores
})

df_preds.to_csv("predictions.csv", index=False)

import os

def save_file_list(folder, filename):
    with open(filename, "w") as f:
        for file in os.listdir(folder):
            f.write(file + "\n")

save_file_list("data/fall_final/train/fall", "train_fall.txt")
save_file_list("data/fall_final/train/normal", "train_normal.txt")

save_file_list("data/fall_final/test/fall", "test_fall.txt")
save_file_list("data/fall_final/test/normal", "test_normal.txt")

import sys
import tensorflow as tf

with open("environment.txt", "w") as f:
    f.write(f"Python: {sys.version}\n")
    f.write(f"TensorFlow: {tf.__version__}\n")

save_path = "/content/drive/MyDrive/research_models/"

import os

save_path = "/content/drive/MyDrive/research_models/"

os.makedirs(save_path, exist_ok=True)

print("Folder created")

model.save(save_path + "fall_model.keras")
baseline_model.save(save_path + "baseline_model.keras")

print("Models saved successfully")

import os
print(os.listdir(save_path))